'use client';

import { useState, useCallback } from 'react';
import Navbar from '@/components/features/landing/Navbar';
import HeroOverlay from '@/components/features/landing/HeroOverlay';
import ScrollAnimation from '@/components/features/landing/ScrollAnimation';
import ScrollIndicator from '@/components/features/landing/ScrollIndicator';
import FeaturesSection from '@/components/features/landing/FeaturesSection';
import Footer from '@/components/features/landing/Footer';

// Frame manifest — generated by scripts/extract-frames.js
const ANIMATION_CONFIG = {
  frameCount: 191,
  basePath: '/animation/frames/',
  prefix: 'frame_',
  format: 'webp',
};

export default function LandingPage() {
  const [progress, setProgress] = useState(0);
  const [animationComplete, setAnimationComplete] = useState(false);

  const handleProgress = useCallback((p: number) => {
    setProgress(p);
  }, []);

  const handleComplete = useCallback(() => {
    setAnimationComplete(true);
  }, []);

  return (
    <main className="relative">
      {/* ===== Scroll-Locked Animation Canvas (fixed, behind everything) ===== */}
      <ScrollAnimation
        frameCount={ANIMATION_CONFIG.frameCount}
        basePath={ANIMATION_CONFIG.basePath}
        prefix={ANIMATION_CONFIG.prefix}
        format={ANIMATION_CONFIG.format}
        totalWheelTravel={5000}
        bufferAhead={40}
        bufferBehind={20}
        lerpFactor={0.1}
        onProgress={handleProgress}
        onComplete={handleComplete}
      />

      {/* ===== Fixed Navigation ===== */}
      <Navbar progress={progress} animationComplete={animationComplete} />

      {/* ===== Hero Text Overlay (appears when ink is dark) ===== */}
      <HeroOverlay progress={progress} />

      {/* ===== Scroll Indicator (fades early) ===== */}
      <ScrollIndicator progress={progress} />

      {/* ===== Content Below Animation ===== */}
      {/* This spacer takes up the viewport height so content starts below the fixed canvas */}
      <div className="h-screen" />

      {/* ===== Features Section — After the Animation ===== */}
      <FeaturesSection />

      {/* ===== Footer ===== */}
      <Footer />
    </main>
  );
}
