/**
 * Schema Modeling — PostgreSQL + Prisma ORM
 * 
 * This file demonstrates relational schema modeling patterns used in HisabKitab.
 * The primary database is PostgreSQL, and Prisma ORM is used for type-safe queries.
 * 
 * Key Modeling Concepts demonstrated:
 *   1. One-to-Many relationships (Shop → Contacts, Contact → Transactions)
 *   2. Many-to-Many via junction table (User → ShopMember → Shop)
 *   3. Composite indexes for query optimization
 *   4. Decimal precision for financial data
 *   5. Soft deletes for audit trail preservation
 *   6. Referential integrity via foreign keys
 * 
 * The Prisma schema lives at: packages/database/prisma/schema.prisma
 * Prisma Client is shared across the monorepo via @hisab-kitab/database
 */

// ─── Example: How Prisma schema maps to PostgreSQL ─────────────────────────
//
// Prisma Schema:
//   model Contact {
//     id        String  @id @default(cuid())
//     shopId    String
//     name      String
//     balance   Decimal @default(0) @db.Decimal(14, 2)
//     shop      Shop    @relation(fields: [shopId], references: [id])
//     transactions Transaction[]
//     @@index([shopId, isDeleted])
//   }
//
// PostgreSQL DDL (generated by Prisma):
//   CREATE TABLE "Contact" (
//     "id"      TEXT NOT NULL,
//     "shopId"  TEXT NOT NULL,
//     "name"    TEXT NOT NULL,
//     "balance" DECIMAL(14,2) NOT NULL DEFAULT 0,
//     CONSTRAINT "Contact_pkey" PRIMARY KEY ("id"),
//     CONSTRAINT "Contact_shopId_fkey" FOREIGN KEY ("shopId") REFERENCES "Shop"("id") ON DELETE CASCADE
//   );
//   CREATE INDEX "Contact_shopId_isDeleted_idx" ON "Contact"("shopId", "isDeleted");
//
// ─── Prisma Query → SQL Translation ────────────────────────────────────────
//
// Prisma:
//   db.contact.findMany({
//     where: { shopId: "shop123", isDeleted: false },
//     include: { transactions: true }
//   })
//
// SQL Generated:
//   SELECT "Contact"."id", "Contact"."name", ...
//   FROM "Contact"
//   LEFT JOIN "Transaction" ON "Contact"."id" = "Transaction"."contactId"
//   WHERE "Contact"."shopId" = 'shop123' AND "Contact"."isDeleted" = false
//

/**
 * Schema design decisions for HisabKitab (PostgreSQL):
 * 
 * 1. Decimal(14,2) for money fields (balance, amount):
 *    - Avoids floating-point precision errors (0.1 + 0.2 ≠ 0.3 in Float)
 *    - Supports values up to ₹99,99,99,99,99,999.99
 * 
 * 2. Foreign keys with ON DELETE CASCADE:
 *    - When a Shop is deleted, all its Contacts and Transactions are also deleted
 *    - Enforces referential integrity at the database level
 * 
 * 3. Composite indexes (@@index([shopId, isDeleted])):
 *    - Most queries filter by shop + non-deleted records
 *    - Without the index, every query scans the entire table
 * 
 * 4. Junction table for Many-to-Many (ShopMember):
 *    - User ↔ Shop is M:N, mediated by ShopMember
 *    - ShopMember stores role (OWNER/STAFF), permissions (JSON), and status
 * 
 * 5. Soft deletes (isDeleted, deletedAt, deletedBy):
 *    - Records are never permanently deleted
 *    - Supports audit trails and "Trash" recovery
 * 
 * 6. Optimistic locking (version field):
 *    - Prevents conflicting concurrent edits
 *    - If version has changed since data was loaded, the update is rejected
 */

export const SCHEMA_DESIGN_NOTES = {
  database: "PostgreSQL",
  orm: "Prisma",
  moneyType: "Decimal(14,2)",
  softDeletes: true,
  auditTrail: true,
  foreignKeys: "CASCADE",
  indexStrategy: "Composite indexes on frequently filtered columns",
};
